# Generated by Django 6.0.7 on 2026-07-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=70)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('estado', models.CharField(choices=[('RJ', 'Rio de Janeiro'), ('SP', 'São Paulo'), ('MG', 'Minas Gerais'), ('ES', 'Espírito Santo'), ('PR', 'Paraná'), ('BA', 'Bahia'), ('RS', 'Rio Grande do Sul')], max_length=2)),
                ('cidade', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], max_length=1)),
                ('contato', models.CharField(choices=[('C', 'Carta'), ('E', 'E-mail'), ('T', 'Telefone'), ('F', 'Fax')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=8)),
            ],
        ),
    ]
