# Generated by Django 6.0.7 on 2026-07-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('preco_compra', models.FloatField()),
                ('preco_venda', models.FloatField()),
                ('cor', models.CharField(choices=[('Azul', 'Azul'), ('Vermelho', 'Vermelho'), ('Verde', 'Verde'), ('Amarelo', 'Amarelo'), ('Branco', 'Branco'), ('Preto', 'Preto'), ('Marrom', 'Marrom')], max_length=20)),
                ('data_fabricacao', models.DateField()),
                ('imagem', models.CharField(max_length=25)),
            ],
        ),
    ]
